    /**
     * Smilies 10/18/2021
     * pack: Alu & BILIBILI
     */

    // eslint-disable-next-line
    const emoticons = {
        'default': [
            { 'text': ':mrgreen:', 'url': 'icon_mrgreen.gif' },
            { 'text': ':neutral:', 'url': 'icon_neutral.gif' },
            { 'text': ':twisted:', 'url': 'icon_twisted.gif' },
            { 'text': ':arrow:', 'url': 'icon_arrow.gif' },
            { 'text': ':shock:', 'url': 'icon_eek.gif' },
            { 'text': ':smile:', 'url': 'icon_smile.gif' },
            { 'text': ':???:', 'url': 'icon_confused.gif' },
            { 'text': ':cool:', 'url': 'icon_cool.gif' },
            { 'text': ':evil:', 'url': 'icon_evil.gif' },
            { 'text': ':grin:', 'url': 'icon_biggrin.gif' },
            { 'text': ':idea:', 'url': 'icon_idea.gif' },
            { 'text': ':oops:', 'url': 'icon_redface.gif' },
            { 'text': ':razz:', 'url': 'icon_razz.gif' },
            { 'text': ':roll:', 'url': 'icon_rolleyes.gif' },
            { 'text': ':wink:', 'url': 'icon_wink.gif' },
            { 'text': ':cry:', 'url': 'icon_cry.gif' },
            { 'text': ':eek:', 'url': 'icon_surprised.gif' },
            { 'text': ':lol:', 'url': 'icon_lol.gif' },
            { 'text': ':mad:', 'url': 'icon_mad.gif' },
            { 'text': ':sad:', 'url': 'icon_sad.gif' },
            { 'text': '8-)', 'url': 'icon_cool.gif' },
            { 'text': '8-O', 'url': 'icon_eek.gif' },
            { 'text': ':-(', 'url': 'icon_sad.gif' },
            { 'text': ':-)', 'url': 'icon_smile.gif' },
            { 'text': ':-?', 'url': 'icon_confused.gif' },
            { 'text': ':-D', 'url': 'icon_biggrin.gif' },
            { 'text': ':-P', 'url': 'icon_razz.gif' },
            { 'text': ':-o', 'url': 'icon_surprised.gif' },
            { 'text': ':-x', 'url': 'icon_mad.gif' },
            { 'text': ':-|', 'url': 'icon_neutral.gif' },
            { 'text': ';-)', 'url': 'icon_wink.gif' },
        ],
        // 'emoji': [
        //     { 'text': '微笑', 'url': 'weixiao.gif' },
        // ],
        'bilibili': [
            { 'text': '( ゜- ゜)つロ', 'url': '' },
            { 'text': '_(:з」∠)_', 'url': '' },
            { 'text': '（⌒▽⌒）', 'url': '' },
            { 'text': '（￣▽￣）', 'url': '' },
            { 'text': '(=・ω・=)', 'url': '' },
            { 'text': '(*°▽°*)八(*°▽°*)♪', 'url': '' },
            { 'text': '✿ヽ(°▽°)ノ✿', 'url': '' },
            { 'text': '(¦3【▓▓】', 'url': '' },
            { 'text': '눈_눈', 'url': '' },
            { 'text': '(ಡωಡ)', 'url': '' },
            { 'text': '_(≧∇≦」∠)_', 'url': '' },
            { 'text': '━━━∑(ﾟ□ﾟ*川━', 'url': '' },
            { 'text': '(｀・ω・´)', 'url': '' },
            { 'text': '(￣3￣)', 'url': '' },
            { 'text': '✧(≖ ◡ ≖✿)', 'url': '' },
            { 'text': '(･∀･)', 'url': '' },
            { 'text': '(〜￣△￣)〜', 'url': '' },
            { 'text': '→_→', 'url': '' },
            { 'text': '(°∀°)ﾉ', 'url': '' },
            { 'text': '╮(￣▽￣)╭', 'url': '' },
            { 'text': '( ´_ゝ｀)', 'url': '' },
            { 'text': '←_←', 'url': '' },
            { 'text': '(;¬_¬)', 'url': '' },
            { 'text': '(ﾟДﾟ≡ﾟдﾟ)!?', 'url': '' },
            { 'text': '( ´･･)ﾉ(._.`)', 'url': '' },
            { 'text': 'Σ(ﾟдﾟ;)', 'url': '' },
            { 'text': 'Σ( ￣□￣||)<', 'url': '' },
            { 'text': '(´；ω；`)', 'url': '' },
            { 'text': '（/TДT)/', 'url': '' },
            { 'text': '(^・ω・^ )', 'url': '' },
            { 'text': '(｡･ω･｡)', 'url': '' },
            { 'text': '(●￣(ｴ)￣●)', 'url': '' },
            { 'text': 'ε=ε=(ノ≧∇≦)ノ', 'url': '' },
            { 'text': '(´･_･`)', 'url': '' },
            { 'text': '(-_-#)', 'url': '' },
            { 'text': '（￣へ￣）', 'url': '' },
            { 'text': '(￣ε(#￣) Σ', 'url': '' },
            { 'text': '(╯°口°)╯(┴—┴', 'url': '' },
            { 'text': 'ヽ(`Д´)ﾉ', 'url': '' },
            { 'text': '>("▔□▔)/', 'url': '' },
            { 'text': '(º﹃º&nbsp;)', 'url': '' },
            { 'text': '(๑>؂<๑）', 'url': '' },
            { 'text': '｡ﾟ(ﾟ´Д｀)ﾟ｡', 'url': '' },
            { 'text': '(∂ω∂)', 'url': '' },
            { 'text': '(┯_┯)', 'url': '' },
            { 'text': '(・ω< )★', 'url': '' },
            { 'text': '( ๑ˊ•̥▵•)੭₎₎', 'url': '' },
            { 'text': '¥ㄟ(´･ᴗ･`)ノ¥', 'url': '' },
            { 'text': 'Σ_(꒪ཀ꒪」∠)_', 'url': '' },
            { 'text': '٩(๛ ˘ ³˘)۶❤', 'url': '' },
            { 'text': '(๑‾᷅^‾᷅๑)', 'url': '' },
        ]
    }

    export default {
        emoticons
    }